refactor: Major refactor of Network code
AlbumsRepositoryDataProvider: now injects an ITunesApi, uses it for both .live and .mainBundleTestData

APIError: renamed to NetworkError, moved to Network.swift.

APIRequest: Added APIRequestError, APIRequestProtocol. Simplified implementation a bit as we weren't using its QueryStringParameters/URLComponents features.

ITunesAPI: Added ITunesApiError, a singleton, injected CodableHelper and moved all the decoding stuff into here from Network for better separation of concerns (Network should be concerned with data pushing, and ItunesAPI should be concerned with being a facade that extrudes Albums)

Network: Added NetworkProtocol, removed the NSObjectProtocol junk because we're not using the delegate methods anyways. No longer concerned with Decodable. Now uses async/await and Results instead of completionHandlers.